#version 430 core
layout (local_size_x = 1, local_size_y = 256, local_size_z = 1) in;
layout (binding = 0, rgba32f) readonly restrict uniform image2D u_src;
layout (binding = 1, rgba32f) writeonly restrict uniform image2D u_dst;
layout (location = 2) uniform int u_width;
void main() {
	int y = int(gl_GlobalInvocationID.y);
	vec4 sum = vec4(0);
	for (int x=0; x<u_width; x+=1) {
		ivec2 coords = ivec2(x,y);
		sum += imageLoad(u_src, coords);
		imageStore(u_dst, coords, sum);
	}
}